apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: db
      labels:
        app: db
    spec:
      template:
        metadata:
          name: db
          app:
            name: db
        spec:
          containers:
            - image: registry.redhat.io/rhel9/postgresql-15:latest
              name: postgres
              memoryLimit: 512Mi
              cpuLimit: 500m
              env:
                - name: POSTGRESQL_USER
                  value: todouser
                - name: POSTGRESQL_PASSWORD
                  value: todopassword
                - name: POSTGRESQL_ADMIN_PASSWORD
                  value: adminpassword
                - name: POSTGRESQL_DATABASE
                  value: todos
              ports:
                - name: postgres-port
                  containerPort: 5432
                  volumeMounts:
                    - name: pg-storage
                      mountPath: /var/lib/pgsql/data
          volumes:
            - name: pg-storage
              persistentVolumeClaim:
                claimName: pg-storage
  - apiVersion: v1
    kind: Service
    metadata:
      name: db
      labels:
        app: db
        name: db
    spec:
      ports:
        - port: 5432
          targetPort: 5432
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pg-storage
      labels:
        app: postgres
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
